<a href="https://colab.research.google.com/github/SHRESHTH121/DL/blob/main/DL_21_KerasTuner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.4.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.19.3)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.1.23)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle) (26.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (2026.5.20)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.5.1)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.10.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.15.0)

In [2]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"shreshthgarg121","key":"bea608024c50f92dddc1897d914b4701"}'}

In [3]:
!kaggle datasets download -d uciml/pima-indians-diabetes-database

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database
License(s): CC0-1.0
Downloading pima-indians-diabetes-database.zip to /content
100% 8.91k/8.91k [00:00<00:00, 25.6MB/s]

In [4]:
import zipfile

In [5]:
with zipfile.ZipFile('pima-indians-diabetes-database.zip', 'r') as zip_ref:
    zip_ref.extractall('pima-indians-diabetes-database_data')

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [9]:
df=pd.read_csv('pima-indians-diabetes-database_data/diabetes.csv')

In [10]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [11]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [17]:
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [16]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [18]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(X)

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1)

In [70]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,Dropout

Now this step is totally dependent on us like how many layers to use, no. of node, which optimizer etc. making this step like trial and error to reach best accuracy therefore we can automate this process using an external library called Keras Tuner to find best suitable params for our model

In [24]:
model=Sequential()
model.add(Dense(32,activation='relu',input_dim=8))
model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

In [26]:
model.fit(batch_size=32,x=X_train,y=y_train,validation_data=(X_test,y_test),epochs=100)

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.6221 - loss: 0.6810 - val_accuracy: 0.5844 - val_loss: 0.6768
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6645 - loss: 0.6257 - val_accuracy: 0.6429 - val_loss: 0.6242
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6971 - loss: 0.5876 - val_accuracy: 0.7403 - val_loss: 0.5837
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7248 - loss: 0.5594 - val_accuracy: 0.7792 - val_loss: 0.5552
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7329 - loss: 0.5376 - val_accuracy: 0.7857 - val_loss: 0.5331
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7410 - loss: 0.5202 - val_accuracy: 0.7987 - val_loss: 0.5192
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7541 - loss: 0.5079 - val_accuracy: 0.8182 - val_loss: 0.5092
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7573 - loss: 0.4978 - val_accuracy: 0.8117 - val_loss: 0.4987
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7671 - loss: 0.4889 - val_accuracy: 0.8117 - val_loss: 0.4941
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4820 - val_accuracy: 0.8117 - val_loss: 0.4883
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4769 - val_accuracy: 0.8117 - val_loss: 0.4844
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4716 - val_accuracy: 0.8052 - val_loss: 0.4815
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4679 - val_accuracy: 0.8117 - val_loss: 0.4805
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4655 - val_accuracy: 0.7987 - val_loss: 0.4822
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4622 - val_accuracy: 0.7987 - val_loss: 0.4784
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4594 - val_accuracy: 0.8052 - val_loss: 0.4780
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4575 - val_accuracy: 0.8052 - val_loss: 0.4762
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4559 - val_accuracy: 0.8117 - val_loss: 0.4759
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4543 - val_accuracy: 0.8052 - val_loss: 0.4751
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7769 - loss: 0.4527 - val_accuracy: 0.8052 - val_loss: 0.4741
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7785 - loss: 0.4511 - val_accuracy: 0.8052 - val_loss: 0.4742
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7769 - loss: 0.4502 - val_accuracy: 0.8052 - val_loss: 0.4745
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7769 - loss: 0.4496 - val_accuracy: 0.8052 - val_loss: 0.4758
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4484 - val_accuracy: 0.8052 - val_loss: 0.4753
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7736 - loss: 0.4474 - val_accuracy: 0.8052 - val_loss: 0.4760
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7752 - loss: 0.4473 - val_accuracy: 0.7922 - val_loss: 0.4751
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7769 - loss: 0.4466 - val_accuracy: 0.8052 - val_loss: 0.4761
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7769 - loss: 0.4454 - val_accuracy: 0.8052 - val_loss: 0.4758
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7785 - loss: 0.4450 - val_accuracy: 0.7922 - val_loss: 0.4751
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7769 - loss: 0.4443 - val_accuracy: 0.7922 - val_loss: 0.4752
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7785 - loss: 0.4440 - val_accuracy: 0.7987 - val_loss: 0.4738
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4439 - val_accuracy: 0.7857 - val_loss: 0.4745
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4426 - val_accuracy: 0.7922 - val_loss: 0.4733
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4420 - val_accuracy: 0.7857 - val_loss: 0.4737
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4415 - val_accuracy: 0.7922 - val_loss: 0.4745
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4411 - val_accuracy: 0.7987 - val_loss: 0.4726
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4402 - val_accuracy: 0.7922 - val_loss: 0.4734
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4396 - val_accuracy: 0.7922 - val_loss: 0.4733
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4393 - val_accuracy: 0.7857 - val_loss: 0.4723
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4386 - val_accuracy: 0.7922 - val_loss: 0.4725
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4380 - val_accuracy: 0.7987 - val_loss: 0.4727
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4375 - val_accuracy: 0.7987 - val_loss: 0.4751
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4376 - val_accuracy: 0.7987 - val_loss: 0.4738
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4367 - val_accuracy: 0.7987 - val_loss: 0.4728
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4361 - val_accuracy: 0.8052 - val_loss: 0.4722
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4356 - val_accuracy: 0.8052 - val_loss: 0.4723
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4350 - val_accuracy: 0.7922 - val_loss: 0.4715
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4345 - val_accuracy: 0.7922 - val_loss: 0.4708
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4341 - val_accuracy: 0.7987 - val_loss: 0.4704
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4334 - val_accuracy: 0.7922 - val_loss: 0.4703
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4333 - val_accuracy: 0.7987 - val_loss: 0.4685
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4322 - val_accuracy: 0.7987 - val_loss: 0.4694
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4320 - val_accuracy: 0.8052 - val_loss: 0.4690
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4322 - val_accuracy: 0.8117 - val_loss: 0.4658
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4311 - val_accuracy: 0.8182 - val_loss: 0.4654
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4302 - val_accuracy: 0.8117 - val_loss: 0.4662
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4304 - val_accuracy: 0.8117 - val_loss: 0.4672
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4298 - val_accuracy: 0.8117 - val_loss: 0.4674
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4291 - val_accuracy: 0.8117 - val_loss: 0.4672
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4287 - val_accuracy: 0.8052 - val_loss: 0.4660
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4284 - val_accuracy: 0.8117 - val_loss: 0.4666
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4280 - val_accuracy: 0.8052 - val_loss: 0.4684
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4278 - val_accuracy: 0.8117 - val_loss: 0.4671
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4272 - val_accuracy: 0.8052 - val_loss: 0.4655
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4267 - val_accuracy: 0.8052 - val_loss: 0.4646
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4267 - val_accuracy: 0.8182 - val_loss: 0.4636
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4261 - val_accuracy: 0.8182 - val_loss: 0.4648
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4256 - val_accuracy: 0.8182 - val_loss: 0.4635
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4260 - val_accuracy: 0.8182 - val_loss: 0.4637
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4254 - val_accuracy: 0.8182 - val_loss: 0.4665
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4246 - val_accuracy: 0.8182 - val_loss: 0.4647
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4241 - val_accuracy: 0.8247 - val_loss: 0.4654
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4249 - val_accuracy: 0.8247 - val_loss: 0.4654
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4245 - val_accuracy: 0.8247 - val_loss: 0.4647
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4235 - val_accuracy: 0.8247 - val_loss: 0.4636
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4230 - val_accuracy: 0.8247 - val_loss: 0.4638
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4226 - val_accuracy: 0.8182 - val_loss: 0.4624
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4231 - val_accuracy: 0.8247 - val_loss: 0.4625
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4220 - val_accuracy: 0.8312 - val_loss: 0.4616
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4216 - val_accuracy: 0.8182 - val_loss: 0.4623
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4213 - val_accuracy: 0.8182 - val_loss: 0.4641
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4213 - val_accuracy: 0.8117 - val_loss: 0.4625
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4209 - val_accuracy: 0.8182 - val_loss: 0.4640
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4208 - val_accuracy: 0.8247 - val_loss: 0.4650
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4205 - val_accuracy: 0.8247 - val_loss: 0.4658
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4204 - val_accuracy: 0.8247 - val_loss: 0.4646
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4200 - val_accuracy: 0.8312 - val_loss: 0.4652
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4192 - val_accuracy: 0.8312 - val_loss: 0.4664
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4198 - val_accuracy: 0.8247 - val_loss: 0.4669
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4194 - val_accuracy: 0.8377 - val_loss: 0.4630
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4183 - val_accuracy: 0.8377 - val_loss: 0.4628
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4183 - val_accuracy: 0.8377 - val_loss: 0.4619
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4176 - val_accuracy: 0.8312 - val_loss: 0.4637
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4185 - val_accuracy: 0.8247 - val_loss: 0.4640
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4173 - val_accuracy: 0.8312 - val_loss: 0.4626
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4173 - val_accuracy: 0.8377 - val_loss: 0.4605
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4171 - val_accuracy: 0.8377 - val_loss: 0.4618
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4165 - val_accuracy: 0.8377 - val_loss: 0.4617
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4162 - val_accuracy: 0.8377 - val_loss: 0.4611
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4164 - val_accuracy: 0.8377 - val_loss: 0.4626



1.   How to select best optimizer
2.   No. of nodes in a layer


1.   How to select no. of layers
2.   All in one model

In [27]:
!pip install -U keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.81.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.1)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.5.20)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 4.9 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [30]:
import kerastuner as kt

# **Finding Best Optimizer**

In [31]:
def build_model(hp):
  model=Sequential()
  model.add(Dense(32,activation='relu',input_dim=8))
  model.add(Dense(1,activation='sigmoid'))

  optimizer=hp.Choice('optimizer',values=['adam','sgd','rmsprop','adadelta'])
  model.compile(optimizer=optimizer,loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [32]:
tuner=kt.RandomSearch(build_model,
                     objective='val_accuracy',
                     max_trials=5)
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Trial 4 Complete [00h 00m 03s]
val_accuracy: 0.7792207598686218

Best val_accuracy So Far: 0.7792207598686218
Total elapsed time: 00h 00m 11s

In [33]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [34]:
model=tuner.get_best_models(num_models=1)[0]

In [37]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [38]:
model.fit(X_train,y_train,batch_size=32,epochs=100,initial_epoch=6,validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.7427 - loss: 0.5134 - val_accuracy: 0.7922 - val_loss: 0.5077
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7573 - loss: 0.4992 - val_accuracy: 0.7922 - val_loss: 0.4994
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7638 - loss: 0.4902 - val_accuracy: 0.7922 - val_loss: 0.4902
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7590 - loss: 0.4827 - val_accuracy: 0.7857 - val_loss: 0.4843
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4776 - val_accuracy: 0.7922 - val_loss: 0.4803
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7671 - loss: 0.4728 - val_accuracy: 0.7857 - val_loss: 0.4773
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7671 - loss: 0.4689 - val_accuracy: 0.7857 - val_loss: 0.4751
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4659 - val_accuracy: 0.7922 - val_loss: 0.4724
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4624 - val_accuracy: 0.7857 - val_loss: 0.4710
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.4599 - val_accuracy: 0.7792 - val_loss: 0.4697
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4579 - val_accuracy: 0.7922 - val_loss: 0.4680
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4558 - val_accuracy: 0.7857 - val_loss: 0.4657
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4544 - val_accuracy: 0.7987 - val_loss: 0.4650
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4528 - val_accuracy: 0.7987 - val_loss: 0.4646
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4518 - val_accuracy: 0.7987 - val_loss: 0.4638
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7671 - loss: 0.4504 - val_accuracy: 0.7987 - val_loss: 0.4640
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7720 - loss: 0.4490 - val_accuracy: 0.7922 - val_loss: 0.4639
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7704 - loss: 0.4479 - val_accuracy: 0.7857 - val_loss: 0.4631
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7704 - loss: 0.4468 - val_accuracy: 0.7857 - val_loss: 0.4630
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7687 - loss: 0.4464 - val_accuracy: 0.7857 - val_loss: 0.4627
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7671 - loss: 0.4454 - val_accuracy: 0.7857 - val_loss: 0.4627
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7655 - loss: 0.4444 - val_accuracy: 0.7857 - val_loss: 0.4629
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7655 - loss: 0.4438 - val_accuracy: 0.7857 - val_loss: 0.4621
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7655 - loss: 0.4434 - val_accuracy: 0.7922 - val_loss: 0.4607
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7752 - loss: 0.4424 - val_accuracy: 0.7922 - val_loss: 0.4605
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4426 - val_accuracy: 0.7922 - val_loss: 0.4601
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.4419 - val_accuracy: 0.7922 - val_loss: 0.4598
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7655 - loss: 0.4409 - val_accuracy: 0.7987 - val_loss: 0.4601
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7638 - loss: 0.4406 - val_accuracy: 0.7987 - val_loss: 0.4594
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4399 - val_accuracy: 0.7987 - val_loss: 0.4599
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4399 - val_accuracy: 0.7987 - val_loss: 0.4596
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4394 - val_accuracy: 0.7987 - val_loss: 0.4600
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4386 - val_accuracy: 0.7987 - val_loss: 0.4612
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4387 - val_accuracy: 0.7987 - val_loss: 0.4608
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4373 - val_accuracy: 0.7987 - val_loss: 0.4605
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4374 - val_accuracy: 0.7987 - val_loss: 0.4609
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4368 - val_accuracy: 0.7987 - val_loss: 0.4605
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4365 - val_accuracy: 0.7987 - val_loss: 0.4603
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4359 - val_accuracy: 0.7922 - val_loss: 0.4597
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7655 - loss: 0.4353 - val_accuracy: 0.7922 - val_loss: 0.4602
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.4353 - val_accuracy: 0.7922 - val_loss: 0.4610
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4349 - val_accuracy: 0.7922 - val_loss: 0.4604
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.4346 - val_accuracy: 0.7922 - val_loss: 0.4612
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4340 - val_accuracy: 0.7922 - val_loss: 0.4613
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4335 - val_accuracy: 0.7922 - val_loss: 0.4603
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4332 - val_accuracy: 0.7922 - val_loss: 0.4600
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4328 - val_accuracy: 0.7922 - val_loss: 0.4595
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4322 - val_accuracy: 0.7922 - val_loss: 0.4599
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4319 - val_accuracy: 0.7922 - val_loss: 0.4608
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4317 - val_accuracy: 0.7922 - val_loss: 0.4609
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4318 - val_accuracy: 0.7922 - val_loss: 0.4613
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4310 - val_accuracy: 0.7922 - val_loss: 0.4610
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4308 - val_accuracy: 0.7922 - val_loss: 0.4606
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4304 - val_accuracy: 0.7922 - val_loss: 0.4612
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4301 - val_accuracy: 0.7922 - val_loss: 0.4620
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4292 - val_accuracy: 0.7922 - val_loss: 0.4614
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4290 - val_accuracy: 0.7922 - val_loss: 0.4614
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4289 - val_accuracy: 0.7922 - val_loss: 0.4616
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4287 - val_accuracy: 0.7922 - val_loss: 0.4611
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4280 - val_accuracy: 0.7922 - val_loss: 0.4604
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4279 - val_accuracy: 0.7922 - val_loss: 0.4606
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4278 - val_accuracy: 0.7922 - val_loss: 0.4612
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4269 - val_accuracy: 0.7922 - val_loss: 0.4617
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4268 - val_accuracy: 0.7922 - val_loss: 0.4615
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4264 - val_accuracy: 0.7922 - val_loss: 0.4612
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4259 - val_accuracy: 0.7922 - val_loss: 0.4623
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4256 - val_accuracy: 0.7922 - val_loss: 0.4621
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4252 - val_accuracy: 0.7922 - val_loss: 0.4620
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4250 - val_accuracy: 0.7987 - val_loss: 0.4629
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4245 - val_accuracy: 0.7987 - val_loss: 0.4630
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4241 - val_accuracy: 0.7987 - val_loss: 0.4629
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4241 - val_accuracy: 0.7922 - val_loss: 0.4641
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4232 - val_accuracy: 0.7922 - val_loss: 0.4635
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4230 - val_accuracy: 0.7922 - val_loss: 0.4631
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4234 - val_accuracy: 0.7922 - val_loss: 0.4625
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4225 - val_accuracy: 0.7922 - val_loss: 0.4636
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4224 - val_accuracy: 0.7987 - val_loss: 0.4637
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4222 - val_accuracy: 0.7987 - val_loss: 0.4629
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4215 - val_accuracy: 0.7987 - val_loss: 0.4634
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4221 - val_accuracy: 0.7987 - val_loss: 0.4633
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4215 - val_accuracy: 0.7987 - val_loss: 0.4639
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4211 - val_accuracy: 0.7922 - val_loss: 0.4645
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4203 - val_accuracy: 0.8117 - val_loss: 0.4647
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4203 - val_accuracy: 0.8052 - val_loss: 0.4651
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4199 - val_accuracy: 0.8052 - val_loss: 0.4662
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4192 - val_accuracy: 0.8052 - val_loss: 0.4652
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4193 - val_accuracy: 0.8052 - val_loss: 0.4650
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4191 - val_accuracy: 0.8117 - val_loss: 0.4656
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4189 - val_accuracy: 0.8117 - val_loss: 0.4660
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4185 - val_accuracy: 0.8117 - val_loss: 0.4672
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4179 - val_accuracy: 0.8117 - val_loss: 0.4684
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4177 - val_accuracy: 0.8052 - val_loss: 0.4683
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4175 - val_accuracy: 0.8117 - val_loss: 0.4672
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4173 - val_accuracy: 0.7987 - val_loss: 0.4676

# **Finding Right no. of nodes per layer**

In [44]:
def build_model(hp):
  model=Sequential()
  units=hp.Int('units',8,128,step=8)
  model.add(Dense(units=units,activation='relu',input_dim=8))
  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [45]:
tuner=kt.RandomSearch(build_model,
                     objective='val_accuracy',
                     max_trials=5,directory='mydir')

In [46]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Trial 5 Complete [00h 00m 02s]
val_accuracy: 0.7727272510528564

Best val_accuracy So Far: 0.798701286315918
Total elapsed time: 00h 00m 13s

In [48]:
tuner.get_best_hyperparameters()[0].values

{'units': 120}

In [49]:
model=tuner.get_best_models(num_models=1)[0]

In [50]:
model.fit(X_train,y_train,batch_size=32,epochs=100,initial_epoch=6,validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 0.7736 - loss: 0.4645 - val_accuracy: 0.8117 - val_loss: 0.4608
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4564 - val_accuracy: 0.8052 - val_loss: 0.4599
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4524 - val_accuracy: 0.7922 - val_loss: 0.4606
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4497 - val_accuracy: 0.7922 - val_loss: 0.4582
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4482 - val_accuracy: 0.7792 - val_loss: 0.4576
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4463 - val_accuracy: 0.7857 - val_loss: 0.4579
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4454 - val_accuracy: 0.7987 - val_loss: 0.4581
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4433 - val_accuracy: 0.7987 - val_loss: 0.4582
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4418 - val_accuracy: 0.7987 - val_loss: 0.4578
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4407 - val_accuracy: 0.7857 - val_loss: 0.4585
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4399 - val_accuracy: 0.7922 - val_loss: 0.4580
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4384 - val_accuracy: 0.7922 - val_loss: 0.4579
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4376 - val_accuracy: 0.7987 - val_loss: 0.4569
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4366 - val_accuracy: 0.7922 - val_loss: 0.4581
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4348 - val_accuracy: 0.7792 - val_loss: 0.4603
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4349 - val_accuracy: 0.7987 - val_loss: 0.4589
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4329 - val_accuracy: 0.7987 - val_loss: 0.4605
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4325 - val_accuracy: 0.7922 - val_loss: 0.4597
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4313 - val_accuracy: 0.7987 - val_loss: 0.4600
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4305 - val_accuracy: 0.7987 - val_loss: 0.4605
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4288 - val_accuracy: 0.7922 - val_loss: 0.4588
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4296 - val_accuracy: 0.7987 - val_loss: 0.4589
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4273 - val_accuracy: 0.7922 - val_loss: 0.4598
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4265 - val_accuracy: 0.8052 - val_loss: 0.4592
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4269 - val_accuracy: 0.8052 - val_loss: 0.4590
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4255 - val_accuracy: 0.8052 - val_loss: 0.4576
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4249 - val_accuracy: 0.7922 - val_loss: 0.4577
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7932 - loss: 0.4239 - val_accuracy: 0.7987 - val_loss: 0.4587
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7964 - loss: 0.4226 - val_accuracy: 0.8052 - val_loss: 0.4592
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4228 - val_accuracy: 0.7987 - val_loss: 0.4601
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4209 - val_accuracy: 0.7987 - val_loss: 0.4596
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4207 - val_accuracy: 0.8052 - val_loss: 0.4587
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7997 - loss: 0.4195 - val_accuracy: 0.7987 - val_loss: 0.4577
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7915 - loss: 0.4193 - val_accuracy: 0.7922 - val_loss: 0.4583
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7997 - loss: 0.4187 - val_accuracy: 0.7922 - val_loss: 0.4591
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4179 - val_accuracy: 0.8117 - val_loss: 0.4601
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4171 - val_accuracy: 0.8117 - val_loss: 0.4617
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4163 - val_accuracy: 0.8117 - val_loss: 0.4606
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4159 - val_accuracy: 0.8182 - val_loss: 0.4618
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4145 - val_accuracy: 0.8052 - val_loss: 0.4621
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4141 - val_accuracy: 0.7857 - val_loss: 0.4617
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4136 - val_accuracy: 0.7857 - val_loss: 0.4619
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4128 - val_accuracy: 0.7922 - val_loss: 0.4600
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4131 - val_accuracy: 0.7922 - val_loss: 0.4602
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4124 - val_accuracy: 0.7922 - val_loss: 0.4596
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4106 - val_accuracy: 0.7922 - val_loss: 0.4590
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4105 - val_accuracy: 0.7922 - val_loss: 0.4586
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4099 - val_accuracy: 0.7857 - val_loss: 0.4558
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4091 - val_accuracy: 0.7922 - val_loss: 0.4556
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4083 - val_accuracy: 0.7922 - val_loss: 0.4564
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4078 - val_accuracy: 0.7922 - val_loss: 0.4569
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4074 - val_accuracy: 0.7857 - val_loss: 0.4583
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4071 - val_accuracy: 0.7857 - val_loss: 0.4577
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4064 - val_accuracy: 0.7922 - val_loss: 0.4544
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8094 - loss: 0.4056 - val_accuracy: 0.7922 - val_loss: 0.4556
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4046 - val_accuracy: 0.7922 - val_loss: 0.4585
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.4046 - val_accuracy: 0.7922 - val_loss: 0.4575
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8094 - loss: 0.4041 - val_accuracy: 0.7857 - val_loss: 0.4579
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.4035 - val_accuracy: 0.7922 - val_loss: 0.4584
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4034 - val_accuracy: 0.7922 - val_loss: 0.4564
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8094 - loss: 0.4024 - val_accuracy: 0.7922 - val_loss: 0.4559
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8111 - loss: 0.4014 - val_accuracy: 0.7987 - val_loss: 0.4545
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.4018 - val_accuracy: 0.8052 - val_loss: 0.4551
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8192 - loss: 0.4013 - val_accuracy: 0.7987 - val_loss: 0.4557
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4005 - val_accuracy: 0.7987 - val_loss: 0.4559
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8192 - loss: 0.3994 - val_accuracy: 0.7987 - val_loss: 0.4570
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.3993 - val_accuracy: 0.7987 - val_loss: 0.4588
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8176 - loss: 0.3983 - val_accuracy: 0.7922 - val_loss: 0.4604
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.3980 - val_accuracy: 0.7922 - val_loss: 0.4592
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8176 - loss: 0.3978 - val_accuracy: 0.7922 - val_loss: 0.4612
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8127 - loss: 0.3980 - val_accuracy: 0.7922 - val_loss: 0.4597
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8127 - loss: 0.3973 - val_accuracy: 0.7987 - val_loss: 0.4608
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3956 - val_accuracy: 0.7987 - val_loss: 0.4636
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.3959 - val_accuracy: 0.8052 - val_loss: 0.4573
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3947 - val_accuracy: 0.7987 - val_loss: 0.4601
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.3956 - val_accuracy: 0.7987 - val_loss: 0.4563
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8192 - loss: 0.3949 - val_accuracy: 0.7987 - val_loss: 0.4570
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8192 - loss: 0.3941 - val_accuracy: 0.8052 - val_loss: 0.4578
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3939 - val_accuracy: 0.7987 - val_loss: 0.4589
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.3937 - val_accuracy: 0.8052 - val_loss: 0.4571
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3921 - val_accuracy: 0.8052 - val_loss: 0.4576
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8176 - loss: 0.3921 - val_accuracy: 0.8052 - val_loss: 0.4591
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.3918 - val_accuracy: 0.8052 - val_loss: 0.4599
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.3917 - val_accuracy: 0.7922 - val_loss: 0.4600
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.3912 - val_accuracy: 0.7987 - val_loss: 0.4595
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.3908 - val_accuracy: 0.8052 - val_loss: 0.4627
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.3905 - val_accuracy: 0.7987 - val_loss: 0.4617
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.3895 - val_accuracy: 0.8052 - val_loss: 0.4661
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3889 - val_accuracy: 0.8117 - val_loss: 0.4651
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.3891 - val_accuracy: 0.8117 - val_loss: 0.4650
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.3880 - val_accuracy: 0.8052 - val_loss: 0.4641
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.3886 - val_accuracy: 0.8117 - val_loss: 0.4624
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8274 - loss: 0.3873 - val_accuracy: 0.7922 - val_loss: 0.4625
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8192 - loss: 0.3867 - val_accuracy: 0.8052 - val_loss: 0.4619

# **How to select no. of layers**

In [54]:
def build_model(hp):
  model=Sequential()
  model.add(Dense(72,activation='relu',input_dim=8))
  for i in range(hp.Int('num_layers',min_value=1,max_value=10)):
    model.add(Dense(72,activation='relu'))

  model.add(Dense(1,activation='sigmoid'))
  model.compile(optimizer='rmsprop',metrics=['accuracy'],loss='binary_crossentropy')
  return model

In [55]:
tuner=kt.RandomSearch(build_model,objective='val_accuracy',max_trials=3,directory='mydir',project_name='proj1')

In [56]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Trial 3 Complete [00h 00m 03s]
val_accuracy: 0.8051947951316833

Best val_accuracy So Far: 0.8051947951316833
Total elapsed time: 00h 00m 12s

In [57]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 6}

In [58]:
model=tuner.get_best_models(num_models=1)[0]

In [59]:
model.fit(X_train,y_train,batch_size=32,epochs=100,initial_epoch=6,validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 5s 65ms/step - accuracy: 0.7866 - loss: 0.4655 - val_accuracy: 0.8182 - val_loss: 0.4664
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8029 - loss: 0.4351 - val_accuracy: 0.7987 - val_loss: 0.4619
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7997 - loss: 0.4278 - val_accuracy: 0.7597 - val_loss: 0.5345
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8160 - loss: 0.4208 - val_accuracy: 0.8052 - val_loss: 0.4940
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8046 - loss: 0.4104 - val_accuracy: 0.8247 - val_loss: 0.4794
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8127 - loss: 0.3998 - val_accuracy: 0.7987 - val_loss: 0.4780
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8306 - loss: 0.3915 - val_accuracy: 0.7792 - val_loss: 0.5184
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8339 - loss: 0.3903 - val_accuracy: 0.8052 - val_loss: 0.4793
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3814 - val_accuracy: 0.7468 - val_loss: 0.5600
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3669 - val_accuracy: 0.8182 - val_loss: 0.4797
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3675 - val_accuracy: 0.7922 - val_loss: 0.4768
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8583 - loss: 0.3484 - val_accuracy: 0.8052 - val_loss: 0.5020
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8599 - loss: 0.3399 - val_accuracy: 0.8182 - val_loss: 0.5377
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8485 - loss: 0.3344 - val_accuracy: 0.6753 - val_loss: 0.6655
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8730 - loss: 0.3221 - val_accuracy: 0.8182 - val_loss: 0.5019
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8583 - loss: 0.3104 - val_accuracy: 0.7792 - val_loss: 0.5247
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8795 - loss: 0.2932 - val_accuracy: 0.7403 - val_loss: 0.6683
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - loss: 0.2935 - val_accuracy: 0.7857 - val_loss: 0.5475
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8844 - loss: 0.2907 - val_accuracy: 0.7857 - val_loss: 0.5415
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9023 - loss: 0.2561 - val_accuracy: 0.7987 - val_loss: 0.5557
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9153 - loss: 0.2317 - val_accuracy: 0.7597 - val_loss: 0.6640
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9072 - loss: 0.2554 - val_accuracy: 0.7727 - val_loss: 0.6572
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9121 - loss: 0.2144 - val_accuracy: 0.7792 - val_loss: 0.6634
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9283 - loss: 0.1960 - val_accuracy: 0.7532 - val_loss: 0.7364
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9300 - loss: 0.2060 - val_accuracy: 0.7792 - val_loss: 0.7142
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9283 - loss: 0.2099 - val_accuracy: 0.7078 - val_loss: 0.7413
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9349 - loss: 0.1723 - val_accuracy: 0.7468 - val_loss: 0.8480
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9300 - loss: 0.1875 - val_accuracy: 0.7597 - val_loss: 0.7564
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9625 - loss: 0.1335 - val_accuracy: 0.8117 - val_loss: 0.7359
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9397 - loss: 0.1778 - val_accuracy: 0.7208 - val_loss: 1.0832
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9511 - loss: 0.1546 - val_accuracy: 0.7143 - val_loss: 0.9508
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9446 - loss: 0.1413 - val_accuracy: 0.7143 - val_loss: 1.1089
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9560 - loss: 0.1308 - val_accuracy: 0.5260 - val_loss: 1.9284
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9528 - loss: 0.1566 - val_accuracy: 0.7078 - val_loss: 1.0334
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9739 - loss: 0.0943 - val_accuracy: 0.7597 - val_loss: 1.0423
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9609 - loss: 0.1171 - val_accuracy: 0.7208 - val_loss: 1.0263
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9625 - loss: 0.1032 - val_accuracy: 0.7403 - val_loss: 1.1617
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9691 - loss: 0.1060 - val_accuracy: 0.7403 - val_loss: 1.0547
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9511 - loss: 0.1176 - val_accuracy: 0.7403 - val_loss: 1.1296
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9756 - loss: 0.0839 - val_accuracy: 0.7403 - val_loss: 1.1192
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9593 - loss: 0.1117 - val_accuracy: 0.7532 - val_loss: 1.0999
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9739 - loss: 0.0852 - val_accuracy: 0.7403 - val_loss: 1.1226
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9756 - loss: 0.0891 - val_accuracy: 0.7338 - val_loss: 1.1372
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9739 - loss: 0.0745 - val_accuracy: 0.7468 - val_loss: 1.1664
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9739 - loss: 0.0822 - val_accuracy: 0.7597 - val_loss: 1.5769
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9707 - loss: 0.0751 - val_accuracy: 0.7468 - val_loss: 1.1578
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9756 - loss: 0.0734 - val_accuracy: 0.6948 - val_loss: 1.4085
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9886 - loss: 0.0432 - val_accuracy: 0.7143 - val_loss: 1.6186
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9756 - loss: 0.0549 - val_accuracy: 0.7662 - val_loss: 1.3459
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9674 - loss: 0.0699 - val_accuracy: 0.7403 - val_loss: 1.4263
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9723 - loss: 0.0748 - val_accuracy: 0.7208 - val_loss: 1.3392
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9788 - loss: 0.0520 - val_accuracy: 0.7273 - val_loss: 1.3512
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9674 - loss: 0.0868 - val_accuracy: 0.7532 - val_loss: 1.3376
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9756 - loss: 0.0428 - val_accuracy: 0.7468 - val_loss: 1.5479
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9756 - loss: 0.0804 - val_accuracy: 0.7468 - val_loss: 1.1914
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0251 - val_accuracy: 0.7597 - val_loss: 1.4074
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0331 - val_accuracy: 0.7727 - val_loss: 1.6105
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9674 - loss: 0.1032 - val_accuracy: 0.7597 - val_loss: 1.3246
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9837 - loss: 0.0464 - val_accuracy: 0.7078 - val_loss: 1.6055
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0123 - val_accuracy: 0.6818 - val_loss: 2.3620
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9658 - loss: 0.1496 - val_accuracy: 0.7208 - val_loss: 1.4986
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0345 - val_accuracy: 0.7143 - val_loss: 1.5230
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9821 - loss: 0.0505 - val_accuracy: 0.7403 - val_loss: 1.7083
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9658 - loss: 0.0958 - val_accuracy: 0.7532 - val_loss: 1.4335
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0079 - val_accuracy: 0.7857 - val_loss: 1.8207
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9691 - loss: 0.0878 - val_accuracy: 0.7532 - val_loss: 1.4801
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0153 - val_accuracy: 0.7403 - val_loss: 1.6051
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9870 - loss: 0.0350 - val_accuracy: 0.7403 - val_loss: 1.8904
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9772 - loss: 0.0797 - val_accuracy: 0.7468 - val_loss: 1.6902
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0268 - val_accuracy: 0.7403 - val_loss: 1.8067
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0315 - val_accuracy: 0.7273 - val_loss: 1.7092
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0247 - val_accuracy: 0.7338 - val_loss: 1.7580
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0190 - val_accuracy: 0.7403 - val_loss: 1.7337
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9739 - loss: 0.1140 - val_accuracy: 0.7338 - val_loss: 2.0010
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9788 - loss: 0.0559 - val_accuracy: 0.7338 - val_loss: 1.6954
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9984 - loss: 0.0164 - val_accuracy: 0.7338 - val_loss: 1.7187
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9984 - loss: 0.0081 - val_accuracy: 0.7273 - val_loss: 1.8446
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9707 - loss: 0.0899 - val_accuracy: 0.7662 - val_loss: 1.6163
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9853 - loss: 0.0567 - val_accuracy: 0.7468 - val_loss: 1.6097
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9935 - loss: 0.0241 - val_accuracy: 0.7597 - val_loss: 1.5697
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9902 - loss: 0.0178 - val_accuracy: 0.6948 - val_loss: 1.7097
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9707 - loss: 0.1024 - val_accuracy: 0.7338 - val_loss: 1.6011
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9951 - loss: 0.0188 - val_accuracy: 0.7338 - val_loss: 1.7082
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0034 - val_accuracy: 0.7468 - val_loss: 1.7768
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9935 - loss: 0.0200 - val_accuracy: 0.7273 - val_loss: 1.7915
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9886 - loss: 0.0421 - val_accuracy: 0.8052 - val_loss: 1.5482
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0209 - val_accuracy: 0.7403 - val_loss: 1.7736
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9870 - loss: 0.0375 - val_accuracy: 0.7597 - val_loss: 1.7183
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0156 - val_accuracy: 0.7468 - val_loss: 1.7064
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0022 - val_accuracy: 0.7403 - val_loss: 1.9262
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9886 - loss: 0.0388 - val_accuracy: 0.7403 - val_loss: 1.9459
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0128 - val_accuracy: 0.7338 - val_loss: 1.9145
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0126 - val_accuracy: 0.7143 - val_loss: 2.0307
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0288 - val_accuracy: 0.7078 - val_loss: 1.9432

# **Everything togather**

In [75]:
def build_model(hp):
  model=Sequential()
  counter=0
  for i in range(hp.Int('num_layers',min_value=1,max_value=10,step=1)):
    if counter==0:
      model.add(Dense(hp.Int('units'+str(i),min_value=8,max_value=128,step=8),
                      activation=hp.Choice('activation'+str(i),values=['relu','sigmoid','tanh']),
                      input_dim=8))
      model.add(Dropout(hp.Choice('dropout'+str(i),values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))
    else:
       model.add(Dense(hp.Int('units'+str(i),min_value=8,max_value=128,step=8),
                      activation=hp.Choice('activation'+str(i),['relu','sigmoid','tanh'])))
       model.add(Dropout(hp.Choice('dropout'+str(i),values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))
    counter+=1

  model.add(Dense(1,activation='sigmoid'))
  model.compile(optimizer=hp.Choice('optimizer',values=['adam','sgd','rmsprop']),loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [76]:
tuner=kt.RandomSearch(build_model,objective='val_accuracy',max_trials=3,directory='mydir',project_name='proj3')

In [77]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Trial 3 Complete [00h 00m 04s]
val_accuracy: 0.6428571343421936

Best val_accuracy So Far: 0.6428571343421936
Total elapsed time: 00h 00m 14s

In [78]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 9,
 'units0': 24,
 'activation0': 'relu',
 'dropout0': 0.3,
 'optimizer': 'adam',
 'units1': 8,
 'activation1': 'relu',
 'dropout1': 0.1,
 'units2': 8,
 'activation2': 'relu',
 'dropout2': 0.1,
 'units3': 8,
 'activation3': 'relu',
 'dropout3': 0.1,
 'units4': 8,
 'activation4': 'relu',
 'dropout4': 0.1,
 'units5': 8,
 'activation5': 'relu',
 'dropout5': 0.1,
 'units6': 8,
 'activation6': 'relu',
 'dropout6': 0.1,
 'units7': 8,
 'activation7': 'relu',
 'dropout7': 0.1,
 'units8': 8,
 'activation8': 'relu',
 'dropout8': 0.1}

In [79]:
model=tuner.get_best_models(num_models=1)[0]

In [80]:
model.fit(X_train,y_train,batch_size=32,epochs=200,initial_epoch=6,validation_data=(X_test,y_test))

Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 4s 19ms/step - accuracy: 0.6531 - loss: 0.6712 - val_accuracy: 0.6429 - val_loss: 0.6615
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6524 - val_accuracy: 0.6429 - val_loss: 0.6429
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6498 - loss: 0.6397 - val_accuracy: 0.6429 - val_loss: 0.6242
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6350 - val_accuracy: 0.6429 - val_loss: 0.6116
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.6242 - val_accuracy: 0.6429 - val_loss: 0.6002
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6243 - val_accuracy: 0.6429 - val_loss: 0.5868
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6515 - loss: 0.6069 - val_accuracy: 0.6429 - val_loss: 0.5831
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6515 - loss: 0.6046 - val_accuracy: 0.6429 - val_loss: 0.5645
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5962 - val_accuracy: 0.6429 - val_loss: 0.5502
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6515 - loss: 0.5903 - val_accuracy: 0.6429 - val_loss: 0.5485
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5824 - val_accuracy: 0.6429 - val_loss: 0.5293
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5669 - val_accuracy: 0.6429 - val_loss: 0.5223
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5584 - val_accuracy: 0.6429 - val_loss: 0.5242
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6531 - loss: 0.5584 - val_accuracy: 0.6429 - val_loss: 0.5210
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5695 - val_accuracy: 0.6429 - val_loss: 0.5215
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5638 - val_accuracy: 0.6429 - val_loss: 0.5197
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5573 - val_accuracy: 0.6429 - val_loss: 0.5159
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5541 - val_accuracy: 0.6429 - val_loss: 0.5226
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5254 - val_accuracy: 0.6429 - val_loss: 0.5116
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5353 - val_accuracy: 0.6429 - val_loss: 0.5096
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6531 - loss: 0.5426 - val_accuracy: 0.6429 - val_loss: 0.5178
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5393 - val_accuracy: 0.6429 - val_loss: 0.5162
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.5377 - val_accuracy: 0.6429 - val_loss: 0.5181
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5339 - val_accuracy: 0.6429 - val_loss: 0.5176
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5341 - val_accuracy: 0.6429 - val_loss: 0.5171
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6792 - loss: 0.5565 - val_accuracy: 0.7857 - val_loss: 0.5231
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6482 - loss: 0.5371 - val_accuracy: 0.7857 - val_loss: 0.5163
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6759 - loss: 0.5363 - val_accuracy: 0.7662 - val_loss: 0.5224
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6922 - loss: 0.5419 - val_accuracy: 0.7662 - val_loss: 0.5268
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7166 - loss: 0.5405 - val_accuracy: 0.7857 - val_loss: 0.5205
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6987 - loss: 0.5204 - val_accuracy: 0.7857 - val_loss: 0.5164
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7134 - loss: 0.5262 - val_accuracy: 0.7857 - val_loss: 0.5183
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7459 - loss: 0.5271 - val_accuracy: 0.7922 - val_loss: 0.5176
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7231 - loss: 0.5388 - val_accuracy: 0.7857 - val_loss: 0.5166
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7134 - loss: 0.5387 - val_accuracy: 0.7792 - val_loss: 0.5178
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7280 - loss: 0.5247 - val_accuracy: 0.7857 - val_loss: 0.5112
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7280 - loss: 0.5312 - val_accuracy: 0.7987 - val_loss: 0.5179
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7410 - loss: 0.5239 - val_accuracy: 0.7792 - val_loss: 0.5135
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7362 - loss: 0.5021 - val_accuracy: 0.7857 - val_loss: 0.5120
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7117 - loss: 0.5219 - val_accuracy: 0.7987 - val_loss: 0.5151
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7199 - loss: 0.5237 - val_accuracy: 0.7987 - val_loss: 0.5224
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7166 - loss: 0.5311 - val_accuracy: 0.7987 - val_loss: 0.5218
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7231 - loss: 0.5174 - val_accuracy: 0.7987 - val_loss: 0.5196
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7264 - loss: 0.5301 - val_accuracy: 0.7857 - val_loss: 0.5238
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7280 - loss: 0.5371 - val_accuracy: 0.7987 - val_loss: 0.5251
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7150 - loss: 0.5355 - val_accuracy: 0.7987 - val_loss: 0.5270
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7280 - loss: 0.5105 - val_accuracy: 0.7987 - val_loss: 0.5219
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7150 - loss: 0.5151 - val_accuracy: 0.7987 - val_loss: 0.5239
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7280 - loss: 0.4959 - val_accuracy: 0.7857 - val_loss: 0.5267
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7296 - loss: 0.5087 - val_accuracy: 0.7792 - val_loss: 0.5291
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7459 - loss: 0.4937 - val_accuracy: 0.7792 - val_loss: 0.5276
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7134 - loss: 0.5193 - val_accuracy: 0.7792 - val_loss: 0.5269
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7248 - loss: 0.5058 - val_accuracy: 0.7792 - val_loss: 0.5260
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7215 - loss: 0.4922 - val_accuracy: 0.7792 - val_loss: 0.5262
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7345 - loss: 0.5222 - val_accuracy: 0.7857 - val_loss: 0.5252
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7394 - loss: 0.5269 - val_accuracy: 0.7792 - val_loss: 0.5264
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7101 - loss: 0.5289 - val_accuracy: 0.7662 - val_loss: 0.5283
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7085 - loss: 0.5279 - val_accuracy: 0.7792 - val_loss: 0.5286
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7280 - loss: 0.5172 - val_accuracy: 0.7857 - val_loss: 0.5289
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7248 - loss: 0.5357 - val_accuracy: 0.7857 - val_loss: 0.5311
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7231 - loss: 0.5163 - val_accuracy: 0.7857 - val_loss: 0.5308
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7476 - loss: 0.5106 - val_accuracy: 0.7922 - val_loss: 0.5239
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7394 - loss: 0.5029 - val_accuracy: 0.8052 - val_loss: 0.5219
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7394 - loss: 0.5094 - val_accuracy: 0.8052 - val_loss: 0.5200
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7296 - loss: 0.5087 - val_accuracy: 0.7987 - val_loss: 0.5220
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7215 - loss: 0.5144 - val_accuracy: 0.8052 - val_loss: 0.5196
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7280 - loss: 0.4931 - val_accuracy: 0.8052 - val_loss: 0.5192
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7476 - loss: 0.5022 - val_accuracy: 0.8052 - val_loss: 0.5153
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7280 - loss: 0.5061 - val_accuracy: 0.7987 - val_loss: 0.5251
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7345 - loss: 0.5057 - val_accuracy: 0.8052 - val_loss: 0.5197
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7459 - loss: 0.5141 - val_accuracy: 0.8117 - val_loss: 0.5167
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7362 - loss: 0.5108 - val_accuracy: 0.8182 - val_loss: 0.5156
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7476 - loss: 0.5050 - val_accuracy: 0.8052 - val_loss: 0.5209
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7394 - loss: 0.4866 - val_accuracy: 0.8182 - val_loss: 0.5164
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7378 - loss: 0.5103 - val_accuracy: 0.7987 - val_loss: 0.5183
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7459 - loss: 0.4871 - val_accuracy: 0.7987 - val_loss: 0.5174
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7476 - loss: 0.5109 - val_accuracy: 0.7987 - val_loss: 0.5173
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7280 - loss: 0.4934 - val_accuracy: 0.7922 - val_loss: 0.5205
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7410 - loss: 0.4970 - val_accuracy: 0.7922 - val_loss: 0.5171
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7264 - loss: 0.5043 - val_accuracy: 0.7987 - val_loss: 0.5147
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7492 - loss: 0.4895 - val_accuracy: 0.8117 - val_loss: 0.5126
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7492 - loss: 0.5040 - val_accuracy: 0.7987 - val_loss: 0.5124
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7280 - loss: 0.4972 - val_accuracy: 0.7922 - val_loss: 0.5127
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7671 - loss: 0.5101 - val_accuracy: 0.7922 - val_loss: 0.5119
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7345 - loss: 0.4988 - val_accuracy: 0.8052 - val_loss: 0.5123
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7443 - loss: 0.5171 - val_accuracy: 0.8052 - val_loss: 0.5138
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7394 - loss: 0.5042 - val_accuracy: 0.8052 - val_loss: 0.5247
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7573 - loss: 0.5048 - val_accuracy: 0.8052 - val_loss: 0.5156
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7524 - loss: 0.4846 - val_accuracy: 0.8052 - val_loss: 0.5181
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7573 - loss: 0.5060 - val_accuracy: 0.8052 - val_loss: 0.5144
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7476 - loss: 0.4982 - val_accuracy: 0.8117 - val_loss: 0.5181
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7443 - loss: 0.5070 - val_accuracy: 0.8052 - val_loss: 0.5114
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7362 - loss: 0.5112 - val_accuracy: 0.8117 - val_loss: 0.5152
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7329 - loss: 0.5307 - val_accuracy: 0.8117 - val_loss: 0.5178
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7541 - loss: 0.4851 - val_accuracy: 0.8182 - val_loss: 0.5100
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7476 - loss: 0.4944 - val_accuracy: 0.8052 - val_loss: 0.5108
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7524 - loss: 0.4943 - val_accuracy: 0.8182 - val_loss: 0.5086
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7378 - loss: 0.5088 - val_accuracy: 0.8247 - val_loss: 0.5079
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7524 - loss: 0.4818 - val_accuracy: 0.8117 - val_loss: 0.5089
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7557 - loss: 0.4958 - val_accuracy: 0.8052 - val_loss: 0.5100
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7606 - loss: 0.4852 - val_accuracy: 0.8247 - val_loss: 0.5107
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7296 - loss: 0.4983 - val_accuracy: 0.8052 - val_loss: 0.5154
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7524 - loss: 0.4924 - val_accuracy: 0.8117 - val_loss: 0.5103
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7443 - loss: 0.4967 - val_accuracy: 0.8182 - val_loss: 0.5083
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7541 - loss: 0.4890 - val_accuracy: 0.8182 - val_loss: 0.5111
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7622 - loss: 0.4841 - val_accuracy: 0.8117 - val_loss: 0.5105
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7541 - loss: 0.4957 - val_accuracy: 0.8182 - val_loss: 0.5140
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7476 - loss: 0.4849 - val_accuracy: 0.8117 - val_loss: 0.5125
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7443 - loss: 0.5015 - val_accuracy: 0.8182 - val_loss: 0.5097
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7410 - loss: 0.5039 - val_accuracy: 0.8182 - val_loss: 0.5084
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7476 - loss: 0.4853 - val_accuracy: 0.8052 - val_loss: 0.5119
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7443 - loss: 0.5111 - val_accuracy: 0.7987 - val_loss: 0.5108
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7427 - loss: 0.4939 - val_accuracy: 0.7987 - val_loss: 0.5125
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7557 - loss: 0.4867 - val_accuracy: 0.7987 - val_loss: 0.5137
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7394 - loss: 0.4835 - val_accuracy: 0.7987 - val_loss: 0.5158
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7329 - loss: 0.4965 - val_accuracy: 0.7922 - val_loss: 0.5151
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7590 - loss: 0.5061 - val_accuracy: 0.7922 - val_loss: 0.5126
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7362 - loss: 0.4945 - val_accuracy: 0.7922 - val_loss: 0.5139
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7557 - loss: 0.4845 - val_accuracy: 0.7922 - val_loss: 0.5124
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7508 - loss: 0.5055 - val_accuracy: 0.7987 - val_loss: 0.5120
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7590 - loss: 0.4900 - val_accuracy: 0.7987 - val_loss: 0.5102
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7443 - loss: 0.4935 - val_accuracy: 0.7987 - val_loss: 0.5108
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7590 - loss: 0.4889 - val_accuracy: 0.7987 - val_loss: 0.5112
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7671 - loss: 0.4725 - val_accuracy: 0.8052 - val_loss: 0.5114
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7508 - loss: 0.4918 - val_accuracy: 0.7987 - val_loss: 0.5110
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.4888 - val_accuracy: 0.8052 - val_loss: 0.5089
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7541 - loss: 0.4695 - val_accuracy: 0.7987 - val_loss: 0.5124
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7524 - loss: 0.4874 - val_accuracy: 0.7792 - val_loss: 0.5195
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7362 - loss: 0.4823 - val_accuracy: 0.7857 - val_loss: 0.5208
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7638 - loss: 0.4788 - val_accuracy: 0.7922 - val_loss: 0.5148
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.5179 - val_accuracy: 0.7857 - val_loss: 0.5157
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7752 - loss: 0.4902 - val_accuracy: 0.8117 - val_loss: 0.5089
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7720 - loss: 0.4856 - val_accuracy: 0.8052 - val_loss: 0.5077
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7492 - loss: 0.4824 - val_accuracy: 0.7987 - val_loss: 0.5088
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7769 - loss: 0.4694 - val_accuracy: 0.7987 - val_loss: 0.5076
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7557 - loss: 0.4967 - val_accuracy: 0.8052 - val_loss: 0.5053
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7492 - loss: 0.5054 - val_accuracy: 0.8052 - val_loss: 0.5104
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7557 - loss: 0.5015 - val_accuracy: 0.8052 - val_loss: 0.5151
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7557 - loss: 0.4763 - val_accuracy: 0.7987 - val_loss: 0.5064
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7736 - loss: 0.4639 - val_accuracy: 0.7857 - val_loss: 0.5074
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7671 - loss: 0.4987 - val_accuracy: 0.7987 - val_loss: 0.5111
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4815 - val_accuracy: 0.7922 - val_loss: 0.5096
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7590 - loss: 0.4826 - val_accuracy: 0.7792 - val_loss: 0.5122
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4860 - val_accuracy: 0.7792 - val_loss: 0.5142
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7638 - loss: 0.4798 - val_accuracy: 0.7987 - val_loss: 0.5166
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7671 - loss: 0.4721 - val_accuracy: 0.8052 - val_loss: 0.5128
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7524 - loss: 0.4819 - val_accuracy: 0.7727 - val_loss: 0.5160
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7638 - loss: 0.4747 - val_accuracy: 0.7922 - val_loss: 0.5175
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7541 - loss: 0.4788 - val_accuracy: 0.7987 - val_loss: 0.5176
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7720 - loss: 0.4685 - val_accuracy: 0.7922 - val_loss: 0.5187
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7736 - loss: 0.4706 - val_accuracy: 0.7987 - val_loss: 0.5178
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7573 - loss: 0.4782 - val_accuracy: 0.7792 - val_loss: 0.5156
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7671 - loss: 0.4765 - val_accuracy: 0.7922 - val_loss: 0.5172
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7720 - loss: 0.4709 - val_accuracy: 0.7857 - val_loss: 0.5160
Epoch 161/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4833 - val_accuracy: 0.7922 - val_loss: 0.5180
Epoch 162/200